---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    backstage.io/kubernetes-id: mywebsiteos
    app.kubernetes.io/name: mywebsiteos
    rht-gitops.com/janus-argocd: mywebsiteos
  name: storeuser-sa
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    backstage.io/kubernetes-id: mywebsiteos
    app.kubernetes.io/name: mywebsiteos
    rht-gitops.com/janus-argocd: mywebsiteos
  name: storeuseradmin-sa
