---
kind: SecurityContextConstraints
apiVersion: security.openshift.io/v1
metadata:
  name: mywebsiteos-scc-storeuser
  labels:
    backstage.io/kubernetes-id: mywebsiteos
    app.kubernetes.io/name: mywebsiteos
    rht-gitops.com/janus-argocd: mywebsiteos
allowHostPID: false
allowHostNetwork: false
allowPrivilegeEscalation: true
allowHostDirVolumePlugin: false
allowHostIPC: false
readOnlyRootFilesystem: false
allowHostPorts: false
allowPrivilegedContainer: false
runAsUser:
  type: MustRunAs
  uid: 10001
seLinuxContext:
  type: RunAsAny
fsGroup:
  type: RunAsAny
supplementalGroups:
  type: RunAsAny
users:
  - system:serviceaccount:saturday-test-k8s2:storeuser-sa
---
kind: SecurityContextConstraints
apiVersion: security.openshift.io/v1
metadata:
  name: mywebsiteos-scc-storeuseradmin
  annotations:
    backstage.io/kubernetes-id: mywebsiteos
allowHostPID: false
allowHostNetwork: false
allowPrivilegeEscalation: true
allowHostDirVolumePlugin: false
allowHostIPC: false
readOnlyRootFilesystem: false
allowHostPorts: false
allowPrivilegedContainer: false
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: RunAsAny
fsGroup:
  type: RunAsAny
supplementalGroups:
  type: RunAsAny
users:
  - system:serviceaccount:saturday-test-k8s2:storeuseradmin-sa
